import { s, c, type t } from "../val.config";
import authorsVal from "./authors.val";

// GENERATED by scripts/handbook-fixture.mjs — do not hand-edit.
// Regenerate with a different size: pnpm handbook generate 4 3

/**
 * A handbook: chapters of sections, with a `preview` at BOTH list levels —
 * declared on the ITEM schemas (the section and the chapter), which is where a
 * preview lives: the containers reify their rows from it.
 *
 * This is the shape the store benchmark exists to measure. Two nested
 * previews mean an UNSCOPED preview of one visible section has to walk
 * every chapter and every section and run the user's closure for each — which is
 * exactly the worst case `packages/ui/spa/stores/architecture.md` names, and the
 * reason `PreviewScope` was added to `packages/core`.
 *
 * The rest of the shape is here so the other walks have real work too:
 * `s.richtext()` bodies for the validation walk, `s.keyOf(authorsVal)` and
 * `s.route()` for the reference scan, and an image per chapter for the file
 * reference scan.
 */
export const handbookSectionSchema = s
  .object({
    heading: s.string().minLength(2),
    body: s.richtext({
      style: { bold: true, italic: true },
      block: { h2: true, ul: true },
      inline: { a: true },
    }),
    /** A route this section points at, so route references have something to find. */
    seeAlso: s.route().nullable(),
  })
  .preview(({ val }) => ({
    title: val.heading,
    // Deliberately reads INTO the richtext: a preview that only returned a
    // string would be cheap in a way a real one is not.
    subtitle: firstText(val.body) ?? null,
  }));

export const handbookChapterSchema = s
  .object({
    title: s.string().minLength(2),
    slug: s.string().regexp(/^[a-z0-9-]+$/),
    summary: s.string().render({ as: "textarea" }),
    owner: s.keyOf(authorsVal),
    sections: s.array(handbookSectionSchema),
  })
  .preview(({ val }) => ({
    title: val.title,
    subtitle: `${val.sections.length} sections`,
  }));

export type HandbookChapter = t.inferSchema<typeof handbookChapterSchema>;

/** The first bit of plain text in a richtext value, for a list subtitle. */
function firstText(body: unknown): string | null {
  if (!Array.isArray(body)) return null;
  for (const block of body) {
    if (block !== null && typeof block === "object") {
      const inner = (block as { children?: unknown }).children;
      if (Array.isArray(inner)) {
        for (const leaf of inner) {
          if (typeof leaf === "string" && leaf.trim().length > 0) {
            return leaf.trim().slice(0, 120);
          }
        }
      }
    }
  }
  return null;
}

export default c.define(
  "/content/handbook.val.ts",
  s.array(handbookChapterSchema),
  [
    {
      title: "Onboarding",
      slug: "onboarding",
      summary:
        "Exceptions exist and are fine, but they have to be written down somewhere findable.",
      owner: "freekh",
      sections: [
        {
          heading: "What this covers",
          body: [
            {
              tag: "p",
              children: [
                "This changed in the last revision, so an older printout may say something different. ",
                "Exceptions exist and are fine, but they have to be written down somewhere findable. ",
              ],
            },
            {
              tag: "p",
              children: [
                "The deadline is the last working day of the month, not the last day. ",
                {
                  tag: "span",
                  styles: ["bold"],
                  children: [
                    "There is a template for this; using it saves a round of comments.",
                  ],
                },
                " ",
              ],
            },
          ],
          seeAlso: "/support/faq",
        },
        {
          heading: "Who to ask",
          body: [
            {
              tag: "p",
              children: [
                "Keep the receipt — reimbursement needs the original, not a photo of a copy. ",
                "If the amount is above the threshold, two approvals are required rather than one. ",
              ],
            },
            {
              tag: "p",
              children: [
                "Ask your team lead first; they can approve most of this without escalating. ",
                "Keep the receipt — reimbursement needs the original, not a photo of a copy. ",
              ],
            },
            {
              tag: "p",
              children: [
                "This changed in the last revision, so an older printout may say something different. ",
                "The deadline is the last working day of the month, not the last day. ",
                "If the amount is above the threshold, two approvals are required rather than one. ",
              ],
            },
          ],
          seeAlso: null,
        },
        {
          heading: "Before you start",
          body: [
            {
              tag: "p",
              children: [
                "The deadline is the last working day of the month, not the last day. ",
                {
                  tag: "span",
                  styles: ["bold"],
                  children: [
                    "Ask your team lead first; they can approve most of this without escalating.",
                  ],
                },
                " ",
                "When in doubt, write it down and ask. A short note now is cheaper than a reconstruction later. ",
              ],
            },
            {
              tag: "ul",
              children: [
                {
                  tag: "li",
                  children: [
                    {
                      tag: "p",
                      children: ["Check the date."],
                    },
                  ],
                },
                {
                  tag: "li",
                  children: [
                    {
                      tag: "p",
                      children: ["Check who signed it."],
                    },
                  ],
                },
              ],
            },
          ],
          seeAlso: "/support/faq",
        },
      ],
    },
    {
      title: "Working hours",
      slug: "working-hours",
      summary:
        "This applies to everyone on a permanent contract, and to consultants where the engagement says so.",
      owner: "kimmid",
      sections: [
        {
          heading: "What this covers",
          body: [
            {
              tag: "p",
              children: [
                "If the amount is above the threshold, two approvals are required rather than one. ",
                "This changed in the last revision, so an older printout may say something different. ",
              ],
            },
            {
              tag: "p",
              children: [
                "Ask your team lead first; they can approve most of this without escalating. ",
                "When in doubt, write it down and ask. A short note now is cheaper than a reconstruction later. ",
                "Anything involving personal data goes past the data protection contact before it starts. ",
                "Anything involving personal data goes past the data protection contact before it starts. ",
              ],
            },
            {
              tag: "ul",
              children: [
                {
                  tag: "li",
                  children: [
                    {
                      tag: "p",
                      children: ["Check the date."],
                    },
                  ],
                },
                {
                  tag: "li",
                  children: [
                    {
                      tag: "p",
                      children: ["Check who signed it."],
                    },
                  ],
                },
              ],
            },
          ],
          seeAlso: null,
        },
        {
          heading: "Who to ask",
          body: [
            {
              tag: "p",
              children: [
                "Exceptions exist and are fine, but they have to be written down somewhere findable. ",
                "The deadline is the last working day of the month, not the last day. ",
                "When in doubt, write it down and ask. A short note now is cheaper than a reconstruction later. ",
              ],
            },
            {
              tag: "p",
              children: [
                "This changed in the last revision, so an older printout may say something different. ",
                "Anything involving personal data goes past the data protection contact before it starts. ",
                "Exceptions exist and are fine, but they have to be written down somewhere findable. ",
                "Anything involving personal data goes past the data protection contact before it starts. ",
              ],
            },
            {
              tag: "p",
              children: [
                "Anything involving personal data goes past the data protection contact before it starts. ",
                "Ask your team lead first; they can approve most of this without escalating. ",
                "Keep the receipt — reimbursement needs the original, not a photo of a copy. ",
              ],
            },
          ],
          seeAlso: null,
        },
        {
          heading: "Before you start",
          body: [
            {
              tag: "p",
              children: [
                "This changed in the last revision, so an older printout may say something different. ",
                {
                  tag: "span",
                  styles: ["bold"],
                  children: [
                    "Keep the receipt — reimbursement needs the original, not a photo of a copy.",
                  ],
                },
                " ",
              ],
            },
          ],
          seeAlso: "/support/faq",
        },
      ],
    },
    {
      title: "Expenses",
      slug: "expenses",
      summary:
        "There is a template for this; using it saves a round of comments.",
      owner: "freekh",
      sections: [
        {
          heading: "What this covers",
          body: [
            {
              tag: "p",
              children: [
                "If the amount is above the threshold, two approvals are required rather than one. ",
                "Keep the receipt — reimbursement needs the original, not a photo of a copy. ",
                "When in doubt, write it down and ask. A short note now is cheaper than a reconstruction later. ",
                "Keep the receipt — reimbursement needs the original, not a photo of a copy. ",
              ],
            },
            {
              tag: "p",
              children: [
                "When in doubt, write it down and ask. A short note now is cheaper than a reconstruction later. ",
                {
                  tag: "span",
                  styles: ["bold"],
                  children: [
                    "If the amount is above the threshold, two approvals are required rather than one.",
                  ],
                },
                " ",
                "There is a template for this; using it saves a round of comments. ",
                "If the amount is above the threshold, two approvals are required rather than one. ",
              ],
            },
          ],
          seeAlso: null,
        },
        {
          heading: "Who to ask",
          body: [
            {
              tag: "p",
              children: [
                "There is a template for this; using it saves a round of comments. ",
                "Anything involving personal data goes past the data protection contact before it starts. ",
                "Keep the receipt — reimbursement needs the original, not a photo of a copy. ",
              ],
            },
            {
              tag: "ul",
              children: [
                {
                  tag: "li",
                  children: [
                    {
                      tag: "p",
                      children: ["Check the date."],
                    },
                  ],
                },
                {
                  tag: "li",
                  children: [
                    {
                      tag: "p",
                      children: ["Check who signed it."],
                    },
                  ],
                },
              ],
            },
          ],
          seeAlso: null,
        },
        {
          heading: "Before you start",
          body: [
            {
              tag: "p",
              children: [
                "Keep the receipt — reimbursement needs the original, not a photo of a copy. ",
                "This applies to everyone on a permanent contract, and to consultants where the engagement says so. ",
                "When in doubt, write it down and ask. A short note now is cheaper than a reconstruction later. ",
                "This applies to everyone on a permanent contract, and to consultants where the engagement says so. ",
              ],
            },
          ],
          seeAlso: null,
        },
      ],
    },
    {
      title: "Travel",
      slug: "travel",
      summary:
        "Keep the receipt — reimbursement needs the original, not a photo of a copy.",
      owner: "kimmid",
      sections: [
        {
          heading: "What this covers",
          body: [
            {
              tag: "p",
              children: [
                "If the amount is above the threshold, two approvals are required rather than one. ",
                "There is a template for this; using it saves a round of comments. ",
              ],
            },
          ],
          seeAlso: null,
        },
        {
          heading: "Who to ask",
          body: [
            {
              tag: "p",
              children: [
                "Ask your team lead first; they can approve most of this without escalating. ",
                "The deadline is the last working day of the month, not the last day. ",
                "This changed in the last revision, so an older printout may say something different. ",
                "This changed in the last revision, so an older printout may say something different. ",
              ],
            },
            {
              tag: "p",
              children: [
                "Ask your team lead first; they can approve most of this without escalating. ",
                {
                  tag: "span",
                  styles: ["bold"],
                  children: [
                    "This changed in the last revision, so an older printout may say something different.",
                  ],
                },
                " ",
                "When in doubt, write it down and ask. A short note now is cheaper than a reconstruction later. ",
              ],
            },
            {
              tag: "p",
              children: [
                "When in doubt, write it down and ask. A short note now is cheaper than a reconstruction later. ",
                {
                  tag: "span",
                  styles: ["bold"],
                  children: [
                    "Ask your team lead first; they can approve most of this without escalating.",
                  ],
                },
                " ",
                "The deadline is the last working day of the month, not the last day. ",
                "If the amount is above the threshold, two approvals are required rather than one. ",
              ],
            },
            {
              tag: "ul",
              children: [
                {
                  tag: "li",
                  children: [
                    {
                      tag: "p",
                      children: ["Check the date."],
                    },
                  ],
                },
                {
                  tag: "li",
                  children: [
                    {
                      tag: "p",
                      children: ["Check who signed it."],
                    },
                  ],
                },
              ],
            },
          ],
          seeAlso: null,
        },
        {
          heading: "Before you start",
          body: [
            {
              tag: "p",
              children: [
                "Keep the receipt — reimbursement needs the original, not a photo of a copy. ",
                "Exceptions exist and are fine, but they have to be written down somewhere findable. ",
                "When in doubt, write it down and ask. A short note now is cheaper than a reconstruction later. ",
                "There is a template for this; using it saves a round of comments. ",
              ],
            },
            {
              tag: "p",
              children: [
                "Exceptions exist and are fine, but they have to be written down somewhere findable. ",
                {
                  tag: "span",
                  styles: ["bold"],
                  children: [
                    "If the amount is above the threshold, two approvals are required rather than one.",
                  ],
                },
                " ",
                "Exceptions exist and are fine, but they have to be written down somewhere findable. ",
              ],
            },
            {
              tag: "p",
              children: [
                "Anything involving personal data goes past the data protection contact before it starts. ",
                {
                  tag: "span",
                  styles: ["bold"],
                  children: [
                    "The deadline is the last working day of the month, not the last day.",
                  ],
                },
                " ",
                "When in doubt, write it down and ask. A short note now is cheaper than a reconstruction later. ",
              ],
            },
          ],
          seeAlso: null,
        },
      ],
    },
  ],
);
