import { s, c, type t } from "../val.config";
import authorsVal from "./authors.val";

// GENERATED by scripts/jsonvalues-fixtures.mjs — do not hand-edit.
// Regenerate with a different size: pnpm fixtures generate 1000

/**
 * A big `.jsonValues()` RECORD (not a router), used by the manual walkthrough
 * in docs/plans/jsonValues-walkthrough.md.
 *
 * Two properties of the ITEM schema are what make it interesting:
 * - `author: s.keyOf(authorsVal)` points OUTWARD at an ordinary module, so
 *   renaming an author is the case where the reference guard MUST load every
 *   entry before it can answer (the load predicate names this module).
 * - `related: s.route()` triggers the route over-approximation: a route schema
 *   records no target module, so renaming ANY route key has to load this module.
 */
export const kbArticleSchema = s.object({
  // The custom validator is here for the walkthrough's custom-validation steps:
  // it can only ever run CLIENT-SIDE from the real schema instance (a serialized
  // schema cannot carry a function), so it is how you see whether that path works.
  // Every generated entry passes it; the walkthrough breaks one on purpose.
  title: s
    .string()
    .minLength(2)
    .validate((src) =>
      src.toLowerCase().includes("forbidden")
        ? "the word 'forbidden' is not allowed in a title"
        : false,
    ),
  body: s.string().render({ as: "textarea" }),
  order: s.number(),
  author: s.keyOf(authorsVal),
  related: s.route(),
});

export type KbArticle = t.inferSchema<typeof kbArticleSchema>;

export default c.define(
  "/content/kb.val.ts",
  s
    .record(kbArticleSchema)
    .jsonValues()
    .preview(({ val }) => ({
      title: val.title,
      subtitle: val.body,
    })),
  {
    "kb-000": c.json(() => import("./kb/entry-000.val.json")),
    "kb-001": c.json(() => import("./kb/entry-001.val.json")),
    "kb-002": c.json(() => import("./kb/entry-002.val.json")),
    "kb-003": c.json(() => import("./kb/entry-003.val.json")),
    "kb-004": c.json(() => import("./kb/entry-004.val.json")),
    "kb-005": c.json(() => import("./kb/entry-005.val.json")),
    "kb-006": c.json(() => import("./kb/entry-006.val.json")),
    "kb-007": c.json(() => import("./kb/entry-007.val.json")),
    "kb-008": c.json(() => import("./kb/entry-008.val.json")),
    "kb-009": c.json(() => import("./kb/entry-009.val.json")),
    "kb-010": c.json(() => import("./kb/entry-010.val.json")),
    "kb-011": c.json(() => import("./kb/entry-011.val.json")),
    "kb-012": c.json(() => import("./kb/entry-012.val.json")),
    "kb-013": c.json(() => import("./kb/entry-013.val.json")),
    "kb-014": c.json(() => import("./kb/entry-014.val.json")),
    "kb-015": c.json(() => import("./kb/entry-015.val.json")),
    "kb-016": c.json(() => import("./kb/entry-016.val.json")),
    "kb-017": c.json(() => import("./kb/entry-017.val.json")),
    "kb-018": c.json(() => import("./kb/entry-018.val.json")),
    "kb-019": c.json(() => import("./kb/entry-019.val.json")),
    "kb-020": c.json(() => import("./kb/entry-020.val.json")),
    "kb-021": c.json(() => import("./kb/entry-021.val.json")),
    "kb-022": c.json(() => import("./kb/entry-022.val.json")),
    "kb-023": c.json(() => import("./kb/entry-023.val.json")),
    "kb-024": c.json(() => import("./kb/entry-024.val.json")),
    "kb-025": c.json(() => import("./kb/entry-025.val.json")),
    "kb-026": c.json(() => import("./kb/entry-026.val.json")),
    "kb-027": c.json(() => import("./kb/entry-027.val.json")),
    "kb-028": c.json(() => import("./kb/entry-028.val.json")),
    "kb-029": c.json(() => import("./kb/entry-029.val.json")),
    "kb-030": c.json(() => import("./kb/entry-030.val.json")),
    "kb-031": c.json(() => import("./kb/entry-031.val.json")),
    "kb-032": c.json(() => import("./kb/entry-032.val.json")),
    "kb-033": c.json(() => import("./kb/entry-033.val.json")),
    "kb-034": c.json(() => import("./kb/entry-034.val.json")),
    "kb-035": c.json(() => import("./kb/entry-035.val.json")),
    "kb-036": c.json(() => import("./kb/entry-036.val.json")),
    "kb-037": c.json(() => import("./kb/entry-037.val.json")),
    "kb-038": c.json(() => import("./kb/entry-038.val.json")),
    "kb-039": c.json(() => import("./kb/entry-039.val.json")),
    "kb-040": c.json(() => import("./kb/entry-040.val.json")),
    "kb-041": c.json(() => import("./kb/entry-041.val.json")),
    "kb-042": c.json(() => import("./kb/entry-042.val.json")),
    "kb-043": c.json(() => import("./kb/entry-043.val.json")),
    "kb-044": c.json(() => import("./kb/entry-044.val.json")),
    "kb-045": c.json(() => import("./kb/entry-045.val.json")),
    "kb-046": c.json(() => import("./kb/entry-046.val.json")),
    "kb-047": c.json(() => import("./kb/entry-047.val.json")),
    "kb-048": c.json(() => import("./kb/entry-048.val.json")),
    "kb-049": c.json(() => import("./kb/entry-049.val.json")),
    "kb-050": c.json(() => import("./kb/entry-050.val.json")),
    "kb-051": c.json(() => import("./kb/entry-051.val.json")),
    "kb-052": c.json(() => import("./kb/entry-052.val.json")),
    "kb-053": c.json(() => import("./kb/entry-053.val.json")),
    "kb-054": c.json(() => import("./kb/entry-054.val.json")),
    "kb-055": c.json(() => import("./kb/entry-055.val.json")),
    "kb-056": c.json(() => import("./kb/entry-056.val.json")),
    "kb-057": c.json(() => import("./kb/entry-057.val.json")),
    "kb-058": c.json(() => import("./kb/entry-058.val.json")),
    "kb-059": c.json(() => import("./kb/entry-059.val.json")),
    "kb-060": c.json(() => import("./kb/entry-060.val.json")),
    "kb-061": c.json(() => import("./kb/entry-061.val.json")),
    "kb-062": c.json(() => import("./kb/entry-062.val.json")),
    "kb-063": c.json(() => import("./kb/entry-063.val.json")),
    "kb-064": c.json(() => import("./kb/entry-064.val.json")),
    "kb-065": c.json(() => import("./kb/entry-065.val.json")),
    "kb-066": c.json(() => import("./kb/entry-066.val.json")),
    "kb-067": c.json(() => import("./kb/entry-067.val.json")),
    "kb-068": c.json(() => import("./kb/entry-068.val.json")),
    "kb-069": c.json(() => import("./kb/entry-069.val.json")),
    "kb-070": c.json(() => import("./kb/entry-070.val.json")),
    "kb-071": c.json(() => import("./kb/entry-071.val.json")),
    "kb-072": c.json(() => import("./kb/entry-072.val.json")),
    "kb-073": c.json(() => import("./kb/entry-073.val.json")),
    "kb-074": c.json(() => import("./kb/entry-074.val.json")),
    "kb-075": c.json(() => import("./kb/entry-075.val.json")),
    "kb-076": c.json(() => import("./kb/entry-076.val.json")),
    "kb-077": c.json(() => import("./kb/entry-077.val.json")),
    "kb-078": c.json(() => import("./kb/entry-078.val.json")),
    "kb-079": c.json(() => import("./kb/entry-079.val.json")),
    "kb-080": c.json(() => import("./kb/entry-080.val.json")),
    "kb-081": c.json(() => import("./kb/entry-081.val.json")),
    "kb-082": c.json(() => import("./kb/entry-082.val.json")),
    "kb-083": c.json(() => import("./kb/entry-083.val.json")),
    "kb-084": c.json(() => import("./kb/entry-084.val.json")),
    "kb-085": c.json(() => import("./kb/entry-085.val.json")),
    "kb-086": c.json(() => import("./kb/entry-086.val.json")),
    "kb-087": c.json(() => import("./kb/entry-087.val.json")),
    "kb-088": c.json(() => import("./kb/entry-088.val.json")),
    "kb-089": c.json(() => import("./kb/entry-089.val.json")),
    "kb-090": c.json(() => import("./kb/entry-090.val.json")),
    "kb-091": c.json(() => import("./kb/entry-091.val.json")),
    "kb-092": c.json(() => import("./kb/entry-092.val.json")),
    "kb-093": c.json(() => import("./kb/entry-093.val.json")),
    "kb-094": c.json(() => import("./kb/entry-094.val.json")),
    "kb-095": c.json(() => import("./kb/entry-095.val.json")),
    "kb-096": c.json(() => import("./kb/entry-096.val.json")),
    "kb-097": c.json(() => import("./kb/entry-097.val.json")),
    "kb-098": c.json(() => import("./kb/entry-098.val.json")),
    "kb-099": c.json(() => import("./kb/entry-099.val.json")),
    "kb-100": c.json(() => import("./kb/entry-100.val.json")),
    "kb-101": c.json(() => import("./kb/entry-101.val.json")),
    "kb-102": c.json(() => import("./kb/entry-102.val.json")),
    "kb-103": c.json(() => import("./kb/entry-103.val.json")),
    "kb-104": c.json(() => import("./kb/entry-104.val.json")),
    "kb-105": c.json(() => import("./kb/entry-105.val.json")),
    "kb-106": c.json(() => import("./kb/entry-106.val.json")),
    "kb-107": c.json(() => import("./kb/entry-107.val.json")),
    "kb-108": c.json(() => import("./kb/entry-108.val.json")),
    "kb-109": c.json(() => import("./kb/entry-109.val.json")),
    "kb-110": c.json(() => import("./kb/entry-110.val.json")),
    "kb-111": c.json(() => import("./kb/entry-111.val.json")),
    "kb-112": c.json(() => import("./kb/entry-112.val.json")),
    "kb-113": c.json(() => import("./kb/entry-113.val.json")),
    "kb-114": c.json(() => import("./kb/entry-114.val.json")),
    "kb-115": c.json(() => import("./kb/entry-115.val.json")),
    "kb-116": c.json(() => import("./kb/entry-116.val.json")),
    "kb-117": c.json(() => import("./kb/entry-117.val.json")),
    "kb-118": c.json(() => import("./kb/entry-118.val.json")),
    "kb-119": c.json(() => import("./kb/entry-119.val.json")),
  },
);
