import { s, c, type t } from "../val.config";
import authorsVal from "./authors.val";

// GENERATED by scripts/jsonvalues-fixtures.mjs — do not hand-edit.
// Regenerate with a different size: pnpm fixtures generate 1000

/**
 * A big `.jsonValues()` RECORD (not a router), used by the manual walkthrough
 * in docs/plans/jsonValues-walkthrough.md.
 *
 * Two properties of the ITEM schema are what make it interesting:
 * - `author: s.keyOf(authorsVal)` points OUTWARD at an ordinary module, so
 *   renaming an author is the case where the reference guard MUST load every
 *   entry before it can answer (the load predicate names this module).
 * - `related: s.route()` triggers the route over-approximation: a route schema
 *   records no target module, so renaming ANY route key has to load this module.
 */
export const kbArticleSchema = s.object({
  // The custom validator is here for the walkthrough's custom-validation steps:
  // it can only ever run CLIENT-SIDE from the real schema instance (a serialized
  // schema cannot carry a function), so it is how you see whether that path works.
  // Every generated entry passes it; the walkthrough breaks one on purpose.
  title: s
    .string()
    .minLength(2)
    .validate((src) =>
      src.toLowerCase().includes("forbidden")
        ? "the word 'forbidden' is not allowed in a title"
        : false,
    ),
  body: s.string().render({ as: "textarea" }),
  order: s.number(),
  author: s.keyOf(authorsVal),
  related: s.route(),
});

export type KbArticle = t.inferSchema<typeof kbArticleSchema>;

export default c.define(
  "/content/kb.val.ts",
  s
    .record(kbArticleSchema)
    .jsonValues()
    .render({
      as: "list",
      select: ({ val }) => ({
        title: val.title,
        subtitle: val.body,
      }),
    }),
  {
    "kb-000": c.json(() => import("./kb/kb-000.val.json")),
    "kb-001": c.json(() => import("./kb/kb-001.val.json")),
    "kb-002": c.json(() => import("./kb/kb-002.val.json")),
    "kb-003": c.json(() => import("./kb/kb-003.val.json")),
    "kb-004": c.json(() => import("./kb/kb-004.val.json")),
    "kb-005": c.json(() => import("./kb/kb-005.val.json")),
    "kb-006": c.json(() => import("./kb/kb-006.val.json")),
    "kb-007": c.json(() => import("./kb/kb-007.val.json")),
    "kb-008": c.json(() => import("./kb/kb-008.val.json")),
    "kb-009": c.json(() => import("./kb/kb-009.val.json")),
    "kb-010": c.json(() => import("./kb/kb-010.val.json")),
    "kb-011": c.json(() => import("./kb/kb-011.val.json")),
    "kb-012": c.json(() => import("./kb/kb-012.val.json")),
    "kb-013": c.json(() => import("./kb/kb-013.val.json")),
    "kb-014": c.json(() => import("./kb/kb-014.val.json")),
    "kb-015": c.json(() => import("./kb/kb-015.val.json")),
    "kb-016": c.json(() => import("./kb/kb-016.val.json")),
    "kb-017": c.json(() => import("./kb/kb-017.val.json")),
    "kb-018": c.json(() => import("./kb/kb-018.val.json")),
    "kb-019": c.json(() => import("./kb/kb-019.val.json")),
    "kb-020": c.json(() => import("./kb/kb-020.val.json")),
    "kb-021": c.json(() => import("./kb/kb-021.val.json")),
    "kb-022": c.json(() => import("./kb/kb-022.val.json")),
    "kb-023": c.json(() => import("./kb/kb-023.val.json")),
    "kb-024": c.json(() => import("./kb/kb-024.val.json")),
    "kb-025": c.json(() => import("./kb/kb-025.val.json")),
    "kb-026": c.json(() => import("./kb/kb-026.val.json")),
    "kb-027": c.json(() => import("./kb/kb-027.val.json")),
    "kb-028": c.json(() => import("./kb/kb-028.val.json")),
    "kb-029": c.json(() => import("./kb/kb-029.val.json")),
    "kb-030": c.json(() => import("./kb/kb-030.val.json")),
    "kb-031": c.json(() => import("./kb/kb-031.val.json")),
    "kb-032": c.json(() => import("./kb/kb-032.val.json")),
    "kb-033": c.json(() => import("./kb/kb-033.val.json")),
    "kb-034": c.json(() => import("./kb/kb-034.val.json")),
    "kb-035": c.json(() => import("./kb/kb-035.val.json")),
    "kb-036": c.json(() => import("./kb/kb-036.val.json")),
    "kb-037": c.json(() => import("./kb/kb-037.val.json")),
    "kb-038": c.json(() => import("./kb/kb-038.val.json")),
    "kb-039": c.json(() => import("./kb/kb-039.val.json")),
    "kb-040": c.json(() => import("./kb/kb-040.val.json")),
    "kb-041": c.json(() => import("./kb/kb-041.val.json")),
    "kb-042": c.json(() => import("./kb/kb-042.val.json")),
    "kb-043": c.json(() => import("./kb/kb-043.val.json")),
    "kb-044": c.json(() => import("./kb/kb-044.val.json")),
    "kb-045": c.json(() => import("./kb/kb-045.val.json")),
    "kb-046": c.json(() => import("./kb/kb-046.val.json")),
    "kb-047": c.json(() => import("./kb/kb-047.val.json")),
    "kb-048": c.json(() => import("./kb/kb-048.val.json")),
    "kb-049": c.json(() => import("./kb/kb-049.val.json")),
    "kb-050": c.json(() => import("./kb/kb-050.val.json")),
    "kb-051": c.json(() => import("./kb/kb-051.val.json")),
    "kb-052": c.json(() => import("./kb/kb-052.val.json")),
    "kb-053": c.json(() => import("./kb/kb-053.val.json")),
    "kb-054": c.json(() => import("./kb/kb-054.val.json")),
    "kb-055": c.json(() => import("./kb/kb-055.val.json")),
    "kb-056": c.json(() => import("./kb/kb-056.val.json")),
    "kb-057": c.json(() => import("./kb/kb-057.val.json")),
    "kb-058": c.json(() => import("./kb/kb-058.val.json")),
    "kb-059": c.json(() => import("./kb/kb-059.val.json")),
    "kb-060": c.json(() => import("./kb/kb-060.val.json")),
    "kb-061": c.json(() => import("./kb/kb-061.val.json")),
    "kb-062": c.json(() => import("./kb/kb-062.val.json")),
    "kb-063": c.json(() => import("./kb/kb-063.val.json")),
    "kb-064": c.json(() => import("./kb/kb-064.val.json")),
    "kb-065": c.json(() => import("./kb/kb-065.val.json")),
    "kb-066": c.json(() => import("./kb/kb-066.val.json")),
    "kb-067": c.json(() => import("./kb/kb-067.val.json")),
    "kb-068": c.json(() => import("./kb/kb-068.val.json")),
    "kb-069": c.json(() => import("./kb/kb-069.val.json")),
    "kb-070": c.json(() => import("./kb/kb-070.val.json")),
    "kb-071": c.json(() => import("./kb/kb-071.val.json")),
    "kb-072": c.json(() => import("./kb/kb-072.val.json")),
    "kb-073": c.json(() => import("./kb/kb-073.val.json")),
    "kb-074": c.json(() => import("./kb/kb-074.val.json")),
    "kb-075": c.json(() => import("./kb/kb-075.val.json")),
    "kb-076": c.json(() => import("./kb/kb-076.val.json")),
    "kb-077": c.json(() => import("./kb/kb-077.val.json")),
    "kb-078": c.json(() => import("./kb/kb-078.val.json")),
    "kb-079": c.json(() => import("./kb/kb-079.val.json")),
    "kb-080": c.json(() => import("./kb/kb-080.val.json")),
    "kb-081": c.json(() => import("./kb/kb-081.val.json")),
    "kb-082": c.json(() => import("./kb/kb-082.val.json")),
    "kb-083": c.json(() => import("./kb/kb-083.val.json")),
    "kb-084": c.json(() => import("./kb/kb-084.val.json")),
    "kb-085": c.json(() => import("./kb/kb-085.val.json")),
    "kb-086": c.json(() => import("./kb/kb-086.val.json")),
    "kb-087": c.json(() => import("./kb/kb-087.val.json")),
    "kb-088": c.json(() => import("./kb/kb-088.val.json")),
    "kb-089": c.json(() => import("./kb/kb-089.val.json")),
    "kb-090": c.json(() => import("./kb/kb-090.val.json")),
    "kb-091": c.json(() => import("./kb/kb-091.val.json")),
    "kb-092": c.json(() => import("./kb/kb-092.val.json")),
    "kb-093": c.json(() => import("./kb/kb-093.val.json")),
    "kb-094": c.json(() => import("./kb/kb-094.val.json")),
    "kb-095": c.json(() => import("./kb/kb-095.val.json")),
    "kb-096": c.json(() => import("./kb/kb-096.val.json")),
    "kb-097": c.json(() => import("./kb/kb-097.val.json")),
    "kb-098": c.json(() => import("./kb/kb-098.val.json")),
    "kb-099": c.json(() => import("./kb/kb-099.val.json")),
    "kb-100": c.json(() => import("./kb/kb-100.val.json")),
    "kb-101": c.json(() => import("./kb/kb-101.val.json")),
    "kb-102": c.json(() => import("./kb/kb-102.val.json")),
    "kb-103": c.json(() => import("./kb/kb-103.val.json")),
    "kb-104": c.json(() => import("./kb/kb-104.val.json")),
    "kb-105": c.json(() => import("./kb/kb-105.val.json")),
    "kb-106": c.json(() => import("./kb/kb-106.val.json")),
    "kb-107": c.json(() => import("./kb/kb-107.val.json")),
    "kb-108": c.json(() => import("./kb/kb-108.val.json")),
    "kb-109": c.json(() => import("./kb/kb-109.val.json")),
    "kb-110": c.json(() => import("./kb/kb-110.val.json")),
    "kb-111": c.json(() => import("./kb/kb-111.val.json")),
    "kb-112": c.json(() => import("./kb/kb-112.val.json")),
    "kb-113": c.json(() => import("./kb/kb-113.val.json")),
    "kb-114": c.json(() => import("./kb/kb-114.val.json")),
    "kb-115": c.json(() => import("./kb/kb-115.val.json")),
    "kb-116": c.json(() => import("./kb/kb-116.val.json")),
    "kb-117": c.json(() => import("./kb/kb-117.val.json")),
    "kb-118": c.json(() => import("./kb/kb-118.val.json")),
    "kb-119": c.json(() => import("./kb/kb-119.val.json")),
  },
);
