packages:
  - packages/core
  - packages/ui
  - packages/shared
  - packages/server
  - packages/next
  - packages/react
  - packages/cli
  - packages/create
  - packages/init
  - packages/eslint-plugin
  - examples/next
  - packages/server/test/example-projects/*

ignoredBuiltDependencies:
  - less
  - unrs-resolver

minimumReleaseAgeExclude:
  - "@valbuild/*"

onlyBuiltDependencies:
  - esbuild
