/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as ValRouteRouteImport } from './routes/val/route'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as ValIndexRouteImport } from './routes/val/index'
import { Route as ValSplatRouteImport } from './routes/val/$'
import { Route as SiteDocsSplatRouteImport } from './routes/_site.docs.$'
import { Route as SitePostsPostIdRouteImport } from './routes/_site.posts.$postId'
import { Route as ApiValSplatRouteImport } from './routes/api/val.$'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const ValRouteRoute = ValRouteRouteImport.update({
  id: '/val',
  path: '/val',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const ValIndexRoute = ValIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ValRouteRoute,
} as any)
const ValSplatRoute = ValSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ValRouteRoute,
} as any)
const SiteDocsSplatRoute = SiteDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => SiteRoute,
} as any)
const SitePostsPostIdRoute = SitePostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => SiteRoute,
} as any)
const ApiValSplatRoute = ApiValSplatRouteImport.update({
  id: '/api/val/$',
  path: '/api/val/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/val': typeof ValRouteRouteWithChildren
  '/': typeof SiteIndexRoute
  '/val/$': typeof ValSplatRoute
  '/val/': typeof ValIndexRoute
  '/docs/$': typeof SiteDocsSplatRoute
  '/posts/$postId': typeof SitePostsPostIdRoute
  '/api/val/$': typeof ApiValSplatRoute
}
export interface FileRoutesByTo {
  '/val/$': typeof ValSplatRoute
  '/': typeof SiteIndexRoute
  '/val': typeof ValIndexRoute
  '/docs/$': typeof SiteDocsSplatRoute
  '/posts/$postId': typeof SitePostsPostIdRoute
  '/api/val/$': typeof ApiValSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/val': typeof ValRouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/val/$': typeof ValSplatRoute
  '/_site/': typeof SiteIndexRoute
  '/val/': typeof ValIndexRoute
  '/_site/docs/$': typeof SiteDocsSplatRoute
  '/_site/posts/$postId': typeof SitePostsPostIdRoute
  '/api/val/$': typeof ApiValSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/val'
    | '/'
    | '/val/$'
    | '/val/'
    | '/docs/$'
    | '/posts/$postId'
    | '/api/val/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/val/$' | '/' | '/val' | '/docs/$' | '/posts/$postId' | '/api/val/$'
  id:
    | '__root__'
    | '/val'
    | '/_site'
    | '/val/$'
    | '/_site/'
    | '/val/'
    | '/_site/docs/$'
    | '/_site/posts/$postId'
    | '/api/val/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ValRouteRoute: typeof ValRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  ApiValSplatRoute: typeof ApiValSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/val': {
      id: '/val'
      path: '/val'
      fullPath: '/val'
      preLoaderRoute: typeof ValRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/val/': {
      id: '/val/'
      path: '/'
      fullPath: '/val/'
      preLoaderRoute: typeof ValIndexRouteImport
      parentRoute: typeof ValRouteRoute
    }
    '/val/$': {
      id: '/val/$'
      path: '/$'
      fullPath: '/val/$'
      preLoaderRoute: typeof ValSplatRouteImport
      parentRoute: typeof ValRouteRoute
    }
    '/_site/docs/$': {
      id: '/_site/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof SiteDocsSplatRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/posts/$postId': {
      id: '/_site/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof SitePostsPostIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/val/$': {
      id: '/api/val/$'
      path: '/api/val/$'
      fullPath: '/api/val/$'
      preLoaderRoute: typeof ApiValSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ValRouteRouteChildren {
  ValSplatRoute: typeof ValSplatRoute
  ValIndexRoute: typeof ValIndexRoute
}

const ValRouteRouteChildren: ValRouteRouteChildren = {
  ValSplatRoute: ValSplatRoute,
  ValIndexRoute: ValIndexRoute,
}

const ValRouteRouteWithChildren = ValRouteRoute._addFileChildren(
  ValRouteRouteChildren,
)

interface SiteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
  SiteDocsSplatRoute: typeof SiteDocsSplatRoute
  SitePostsPostIdRoute: typeof SitePostsPostIdRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
  SiteDocsSplatRoute: SiteDocsSplatRoute,
  SitePostsPostIdRoute: SitePostsPostIdRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ValRouteRoute: ValRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  ApiValSplatRoute: ApiValSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
