/**
 * The half of the build that needs Node.
 *
 * A project's dependency layer is built from its `node_modules` with the
 * native bundler, its route tree is generated by TanStack's own generator, and
 * both of those read a filesystem. None of it can run in the tab that runs the
 * rest of the build, which is the whole reason this is a separate entrypoint
 * rather than a few more exports: importing it pulls `rolldown` and
 * `@tanstack/router-generator` in, and `@valbuild/ui` ships to a browser.
 *
 * Nothing in here is reachable from the package root. See
 * `noNodeFromBrowser.test.ts`.
 */
export {
  BASE_PROVIDED,
  auditableImports,
  auditableSpecifiers,
  buildVendorLayer,
  chunkNameFor,
  collectDependencyCss,
  cssSpecifiersOf,
  layerDepsOf,
  packageOf,
  type VendorLayer,
  type VendorPlatform,
} from "./vendorLayer";
export { nodeShims } from "./nodeShims";
export { cssModuleLoader } from "./cssModules";
export { routeSplitter } from "./routeSplitter";
export { generateRouteTree, isFileBased } from "./routes";
