/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [__dirname + "/spa/**/*.{js,ts,jsx,tsx}"],
  darkMode: ["class", '[data-mode="dark"]'],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
        md: "1000px",
      },
    },
    zIndex: {
      hover: 1,
      window: 2,
      full: 3,
      overlay: 4,
      5: 5,
      50: 50,
    },

    fontFamily: {
      sans: "'Roboto', sans-serif",
      serif: "'Space Mono', monospace",
    },
    extend: {
      colors: {
        "bg-active": "var(--colors-gray-dark-mode-gray-800)",
        "bg-brand-primary_alt": "var(--colors-gray-dark-mode-gray-800)",
        "bg-brand-primary": "var(--colors-brand-purple-500)",
        "bg-brand-secondary": "var(--colors-brand-purple-600)",
        "bg-brand-solid_hover": "var(--colors-brand-purple-500)",
        "bg-brand-solid": "var(--colors-brand-purple-600)",
        "bg-disabled_subtle": "var(--colors-gray-dark-mode-gray-800)",
        "bg-disabled": "var(--colors-gray-dark-mode-gray-800)",
        "bg-error-primary": "var(--colors-error-red-500)",
        "bg-error-secondary": "var(--colors-error-red-600)",
        "bg-error-solid": "var(--colors-error-red-600)",
        "bg-overlay": "var(--colors-gray-dark-mode-gray-800)",
        "bg-primary_hover": "var(--colors-gray-dark-mode-gray-800)",
        "bg-primary-solid": "var(--colors-gray-dark-mode-gray-900)",
        "bg-primary": "var(--colors-gray-dark-mode-gray-950)",
        "bg-quartenary": "var(--colors-gray-dark-mode-gray-700)",
        "bg-secondary_alt": "var(--colors-gray-dark-mode-gray-950)",
        "bg-secondary_hover": "var(--colors-gray-dark-mode-gray-800)",
        "bg-secondary_subtle": "var(--colors-gray-dark-mode-gray-900)",
        "bg-secondary-solid": "var(--colors-gray-dark-mode-gray-600)",
        "bg-secondary": "var(--colors-gray-dark-mode-gray-900)",
        "bg-success-primary": "var(--colors-success-green-500)",
        "bg-success-secondary": "var(--colors-success-green-600)",
        "bg-success-solid": "var(--colors-success-green-600);   ",
        "bg-tertiary": "var(--colors-gray-dark-mode-gray-800)",
        "bg-warning-primary": "var(--colors-warning-yellow-500)",
        "bg-warning-secondary": "var(--colors-warning-yellow-600)",
        "bg-warning-solid": "var(--colors-warning-yellow-600)",
        "border-brand_alt": "var(--colors-gray-dark-mode-gray-700)",
        "border-brand": "var(--colors-brand-purple-400)",
        "border-disabled_subtle": "var(--colors-gray-dark-mode-gray-800)",
        "border-disabled": "var(--colors-gray-dark-mode-gray-700)",
        "border-error_subtle": "var(--colors-error-red-400)",
        "border-error": "var(--colors-error-red-400)",
        "border-primary": "var(--colors-gray-dark-mode-gray-700)",
        "border-secondary": "var(--colors-gray-dark-mode-gray-800)",
        "border-tertiary": "var(--colors-gray-dark-mode-gray-800)",
        "fg-brand-primary_alt": "var(--colors-gray-dark-mode-gray-300)",
        "fg-brand-primary": "var(--colors-brand-purple-500)",
        "fg-brand-sencondary": "var(--colors-brand-purple-500)",
        "fg-disabled_subtle": "var(--colors-gray-dark-mode-gray-600)",
        "fg-disabled": "var(--colors-gray-dark-mode-gray-500)",
        "fg-error-primary": "var(--colors-error-red-500)",
        "fg-error-secondary": "var(--colors-error-red-400)",
        "fg-primary": "var(--colors-base-white)",
        "fg-quartenary_hover": "var(--colors-gray-dark-mode-gray-300)",
        "fg-quartenary": "var(--colors-gray-dark-mode-gray-400)",
        "fg-quinary_hover": "var(--colors-gray-dark-mode-gray-400)",
        "fg-quinary": "var(--colors-gray-dark-mode-gray-500)",
        "fg-secondary_hover": "var(--colors-gray-dark-mode-gray-200)",
        "fg-secondary": "var(--colors-gray-dark-mode-gray-300)",
        "fg-senary": "var(--colors-gray-dark-mode-gray-600)",
        "fg-success-primary": "var(--colors-success-green-500)",
        "fg-success-secondary": "var(--colors-success-green-400)",
        "fg-tertiary_hover": "var(--colors-gray-dark-mode-gray-300)",
        "fg-tertiary": "var(--colors-gray-dark-mode-gray-400)",
        "fg-warning-primary": "var(--colors-warning-yellow-500)",
        "fg-warning-secondary": "var(--colors-warning-yellow-400)",
        "fg-white": "var(--colors-base-white)",
        "text-brand-primary": "var(--colors-gray-dark-mode-gray-50)",
        "text-brand-secondary": "var(--colors-gray-dark-mode-gray-300)",
        "text-brand-tertiary_alt": "var(--colors-gray-dark-mode-gray-50)",
        "text-brand-tertiary": "var(--colors-gray-dark-mode-gray-400)",
        "text-disabled": "var(--colors-gray-dark-mode-gray-500)",
        "text-error-primary": "var(--colors-error-red-400)",
        "text-placeholder_subtle": "var(--colors-gray-dark-mode-gray-700)",
        "text-placeholder": "var(--colors-gray-dark-mode-gray-400)",
        "text-primary_on-brand": "var(--colors-gray-dark-mode-gray-50)",
        "text-primary": "var(--colors-gray-dark-mode-gray-50)",
        "text-quartenary_on-brand": "var(--colors-gray-dark-mode-gray-400)",
        "text-quartenary": "var(--colors-gray-dark-mode-gray-400)",
        "text-secondary_hover": "var(--colors-gray-dark-mode-gray-200)",
        "text-secondary_on-brand": "var(--colors-gray-dark-mode-gray-300)",
        "text-secondary": "var(--colors-gray-dark-mode-gray-300)",
        "text-success-primary": "var(--colors-success-green-400)",
        "text-tertiary_hover": "var(--colors-gray-dark-mode-gray-300)",
        "text-tertiary_on-brand": "var(--colors-gray-dark-mode-gray-400)",
        "text-tertiary": "var(--colors-gray-dark-mode-gray-400)",
        "text-warning-primary": "var(--colors-warning-yellow-400)",
        "text-white": "var(--colors-base-white)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
