/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [__dirname + "/spa/**/*.{js,ts,jsx,tsx}"],
  darkMode: ["class", '[data-mode="dark"]'],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
        md: "1000px",
      },
    },
    zIndex: {
      hover: 1,
      window: 2,
      full: 3,
      overlay: 4,
      5: 5,
      50: 50,
    },

    fontFamily: {
      sans: "'DM Sans', sans-serif",
      serif: "'Space Grotesk', sans-serif",
    },
    extend: {
      colors: {
        "bg-brand-primary": "var(--bg-brand-primary)",
        "bg-brand-secondary": "var(--bg-brand-secondary)",
        "bg-disabled": "var(--bg-disabled)",
        "bg-error-primary": "var(--bg-error-primary)",
        "bg-error-secondary": "var(--bg-error-secondary)",
        "bg-error-solid": "var(--bg-error-solid)",
        "bg-primary": "var(--bg-primary)",
        "bg-primary-solid": "var(--bg-primary-solid)",
        "bg-primary_hover": "var(--bg-primary_hover)",
        "bg-quaternary": "var(--bg-quaternary)",
        "bg-secondary": "var(--bg-secondary)",
        "bg-secondary-solid": "var(--bg-secondary-solid)",
        "bg-secondary_alt": "var(--bg-secondary_alt)",
        "bg-secondary_hover": "var(--bg-secondary_hover)",
        "bg-secondary_subtle": "var(--bg-secondary_subtle)",
        "bg-selection": "var(--bg-selection)",
        "bg-tertiary": "var(--bg-tertiary)",
        "bg-warning-primary": "var(--bg-warning-primary)",
        "border-error": "var(--border-error)",
        "border-primary": "var(--border-primary)",
        "border-secondary": "var(--border-secondary)",
        "fg-brand-primary": "var(--fg-brand-primary)",
        "fg-brand-secondary": "var(--fg-brand-secondary)",
        "fg-disabled": "var(--fg-disabled)",
        "fg-error-primary": "var(--fg-error-primary)",
        "fg-error-secondary": "var(--fg-error-secondary)",
        "fg-primary": "var(--fg-primary)",
        "fg-quaternary": "var(--fg-quaternary)",
        "fg-secondary": "var(--fg-secondary)",
        "fg-tertiary": "var(--fg-tertiary)",
        "text-brand-primary": "var(--text-brand-primary)",
        "text-brand-secondary": "var(--text-brand-secondary)",
        "text-disabled": "var(--text-disabled)",
        "text-error-primary": "var(--text-error-primary)",
        "text-primary": "var(--text-primary)",
        "text-quaternary": "var(--text-quaternary)",
        "text-secondary": "var(--text-secondary)",
        "text-secondary_hover": "var(--text-secondary_hover)",
        "text-selection": "var(--text-selection)",
        "text-tertiary": "var(--text-tertiary)",
        "text-white": "var(--text-white)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
