/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [__dirname + "/spa/**/*.{js,ts,jsx,tsx}"],
  darkMode: ["class", '[data-mode="dark"]'],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
        md: "1000px",
      },
    },
    zIndex: {
      hover: 1,
      window: 2,
      full: 3,
      overlay: 4,
      5: 5,
      50: 50,
    },

    fontFamily: {
      sans: "'DM Sans', sans-serif",
      serif: "'Space Grotesk', sans-serif",
    },
    extend: {
      colors: {
        "bg-active": "var(--bg-active)",
        "bg-brand-primary_alt": "var(--bg-brand-primary_alt)",
        "bg-brand-primary": "var(--bg-brand-primary)",
        "bg-brand-secondary": "var(--bg-brand-secondary)",
        "bg-brand-solid_hover": "var(--bg-brand-solid_hover)",
        "bg-brand-solid": "var(--bg-brand-solid)",
        "bg-disabled_subtle": "var(--bg-disabled_subtle)",
        "bg-disabled": "var(--bg-disabled)",
        "bg-error-primary": "var(--bg-error-primary)",
        "bg-error-secondary": "var(--bg-error-secondary)",
        "bg-error-solid": "var(--bg-error-solid)",
        "bg-overlay": "var(--bg-overlay)",
        "bg-primary_hover": "var(--bg-primary_hover)",
        "bg-primary-solid": "var(--bg-primary-solid)",
        "bg-primary": "var(--bg-primary)",
        "bg-quartenary": "var(--bg-quartenary)",
        "bg-secondary_alt": "var(--bg-secondary_alt)",
        "bg-secondary_hover": "var(--bg-secondary_hover)",
        "bg-secondary_subtle": "var(--bg-secondary_subtle)",
        "bg-secondary-solid": "var(--bg-secondary-solid)",
        "bg-secondary": "var(--bg-secondary)",
        "bg-success-primary": "var(--bg-success-primary)",
        "bg-success-secondary": "var(--bg-success-secondary)",
        "bg-success-solid": "var(--bg-success-solid ",
        "bg-tertiary": "var(--bg-tertiary)",
        "bg-warning-primary": "var(--bg-warning-primary)",
        "bg-warning-secondary": "var(--bg-warning-secondary)",
        "bg-warning-solid": "var(--bg-warning-solid)",
        "border-brand_alt": "var(--border-brand_alt)",
        "border-brand": "var(--border-brand)",
        "border-disabled_subtle": "var(--border-disabled_subtle)",
        "border-disabled": "var(--border-disabled)",
        "border-error": "var(--border-error)",
        "border-primary": "var(--border-primary)",
        "border-secondary": "var(--border-secondary)",
        "border-tertiary": "var(--border-tertiary)",
        "fg-brand-primary_alt": "var(--fg-brand-primary_alt)",
        "fg-brand-primary": "var(--fg-brand-primary)",
        "fg-brand-sencondary": "var(--fg-brand-sencondary)",
        "fg-disabled_subtle": "var(--fg-disabled_subtle)",
        "fg-disabled": "var(--fg-disabled)",
        "fg-error-primary": "var(--fg-error-primary)",
        "fg-error-secondary": "var(--fg-error-secondary)",
        "fg-primary": "var(--fg-primary)",
        "fg-quartenary_hover": "var(--fg-quartenary_hover)",
        "fg-quartenary": "var(--fg-quartenary)",
        "fg-quinary_hover": "var(--fg-quinary_hover)",
        "fg-quinary": "var(--fg-quinary)",
        "fg-secondary_hover": "var(--fg-secondary_hover)",
        "fg-secondary": "var(--fg-secondary)",
        "fg-senary": "var(--fg-senary)",
        "fg-success-primary": "var(--fg-success-primary)",
        "fg-success-secondary": "var(--fg-success-secondary)",
        "fg-tertiary_hover": "var(--fg-tertiary_hover)",
        "fg-tertiary": "var(--fg-tertiary)",
        "fg-warning-primary": "var(--fg-warning-primary)",
        "fg-warning-secondary": "var(--fg-warning-secondary)",
        "fg-white": "var(--fg-white)",
        "text-brand-primary": "var(--text-brand-primary)",
        "text-brand-secondary": "var(--text-brand-secondary)",
        "text-brand-tertiary_alt": "var(--text-brand-tertiary_alt)",
        "text-brand-tertiary": "var(--text-brand-tertiary)",
        "text-disabled": "var(--text-disabled)",
        "text-error-primary": "var(--text-error-primary)",
        "text-placeholder_subtle": "var(--text-placeholder_subtle)",
        "text-placeholder": "var(--text-placeholder)",
        "text-primary_on-brand": "var(--text-primary_on-brand)",
        "text-primary": "var(--text-primary)",
        "text-quartenary_on-brand": "var(--text-quartenary_on-brand)",
        "text-quartenary": "var(--text-quartenary)",
        "text-secondary_hover": "var(--text-secondary_hover)",
        "text-secondary_on-brand": "var(--text-secondary_on-brand)",
        "text-secondary": "var(--text-secondary)",
        "text-success-primary": "var(--text-success-primary)",
        "text-tertiary_hover": "var(--text-tertiary_hover)",
        "text-tertiary_on-brand": "var(--text-tertiary_on-brand)",
        "text-tertiary": "var(--text-tertiary)",
        "text-warning-primary": "var(--text-warning-primary)",
        "text-white": "var(--text-white)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
