// Inlines Tailwind's own stylesheets into a module the build can import.
//
// The build runs in two places -- a browser tab and Node -- and neither can be
// given a filesystem read that works in both. Tailwind ships these as plain
// .css files, so they are turned into strings here, once, and the generated
// module ships in this package. That also makes them part of the pinned set:
// the Tailwind version a project compiles against is this package's, exactly
// like React is the platform's.
//
// Regenerate with `pnpm --filter @valbuild/tanstack-build build:tailwind`,
// which is a thing to do when `tailwindcss` is bumped and at no other time.
import { createRequire } from "node:module";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

// An async main rather than top-level await: `tsx` loads this through the CJS
// loader, which refuses a module that awaits at the top level with
// ERR_REQUIRE_ASYNC_MODULE.
async function main() {
  const require = createRequire(path.join(__dirname, "package.json"));
  const pkgDir = path.dirname(require.resolve("tailwindcss/package.json"));
  const out = path.join(__dirname, "..", "src", "tailwindSources.gen.ts");

  // The four entrypoints Tailwind's own `@import` graph reaches for.
  const SHEETS = ["index", "preflight", "theme", "utilities"];

  const version = JSON.parse(
    await readFile(path.join(pkgDir, "package.json"), "utf8"),
  ).version;
  const entries: Array<string> = [];
  let total = 0;
  for (const name of SHEETS) {
    const content = await readFile(path.join(pkgDir, `${name}.css`), "utf8");
    total += content.length;
    entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(content)},`);
  }

  await writeFile(
    out,
    `// GENERATED by packages/tanstack-build/scripts/tailwindSources.ts -- do not edit.\n` +
      `// Tailwind ${version}'s own stylesheets, inlined so the build needs no\n` +
      `// filesystem. Regenerate with \`pnpm build:tailwind\`.\n` +
      `export const TAILWIND_VERSION = ${JSON.stringify(version)};\n` +
      `export const TAILWIND_SOURCES: Record<string, string> = {\n${entries.join("\n")}\n};\n`,
  );

  console.log(
    `tailwind ${version}: ${SHEETS.length} stylesheets, ${(total / 1024).toFixed(0)} kB inlined`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
